# Generated by Django 4.2 on 2023-04-08 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_comment_post_alter_student_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gander',
        ),
        migrations.RemoveField(
            model_name='student',
            name='lavel',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Gander',
        ),
        migrations.DeleteModel(
            name='Lavel',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
