# Generated by Django 4.2 on 2023-04-08 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0008_remove_student_admin_remove_student_gander_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gander',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male_famale', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_lavel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('slug_name', models.SlugField()),
                ('age', models.PositiveIntegerField(default=0)),
                ('data_time', models.DateTimeField(auto_now_add=True)),
                ('payment', models.BooleanField(default=False)),
                ('like', models.PositiveIntegerField(default=0)),
                ('img', models.ImageField(blank=True, upload_to='photos/')),
                ('descrition', models.TextField()),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gander', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.gander')),
                ('lavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.lavel')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('coments', models.TextField()),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentary', to='main_app.student')),
            ],
        ),
    ]
