# Generated by Django 4.2 on 2023-04-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_student_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='commentarya',
            field=models.TextField(blank=True),
        ),
    ]
