# Generated by Django 4.2 on 2023-04-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_student_commentarya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
