# Generated by Django 4.2 on 2023-04-09 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_comment_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='img',
        ),
    ]
