# Generated by Django 4.2 on 2023-05-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_student_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.ImageField(blank=True, default='media/photos/img.JPG.jpg', upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='like',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
