# Generated by Django 4.2 on 2023-05-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_student_img_alter_student_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.ImageField(blank=True, default='photos/img.JPG.jpg', upload_to='photos/'),
        ),
    ]
